/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.program.transform;

import org.unidal.workspace.program.IVisitor;
import org.unidal.workspace.program.entity.Block;
import org.unidal.workspace.program.entity.Instrument;
import org.unidal.workspace.program.entity.Program;
import org.unidal.workspace.program.entity.Status;

public abstract class BaseVisitor implements IVisitor {
   @Override
   public void visitBlock(Block block) {
      for (Instrument instrument : block.getInstruments()) {
         visitInstrument(instrument);
      }

      for (Block block_ : block.getBlocks()) {
         visitBlock(block_);
      }

      if (block.getStatus() != null) {
         visitStatus(block.getStatus());
      }
   }

   @Override
   public void visitInstrument(Instrument instrument) {
   }

   @Override
   public void visitProgram(Program program) {
      for (Block block_ : program.getBlocks()) {
         visitBlock(block_);
      }
   }

   @Override
   public void visitStatus(Status status) {
   }
}
