/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.program.transform;

import java.util.ArrayList;
import java.util.List;
import org.unidal.workspace.program.entity.Block;
import org.unidal.workspace.program.entity.Instrument;
import org.unidal.workspace.program.entity.Program;

public class DefaultLinker {
   @SuppressWarnings("unused")
   private boolean m_deferrable;

   private List<Runnable> m_deferedJobs = new ArrayList<Runnable>();

   public DefaultLinker(boolean deferrable) {
      m_deferrable = deferrable;
   }

   public void finish() {
      for (Runnable job : m_deferedJobs) {
         job.run();
      }
   }

   public boolean onBlock(final Program parent, final Block block) {
      parent.addBlock(block);
      return true;
   }

   public boolean onBlock(final Block parent, final Block block) {
      parent.addBlock(block);
      return true;
   }

   public boolean onInstrument(final Block parent, final Instrument instrument) {
      parent.addInstrument(instrument);
      return true;
   }
}
