/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.program.transform;

import static org.unidal.workspace.program.Constants.ELEMENT_DEPEND_ON;
import static org.unidal.workspace.program.Constants.ELEMENT_DEPEND_ONS;
import static org.unidal.workspace.program.Constants.ELEMENT_MESSAGE;
import static org.unidal.workspace.program.Constants.ELEMENT_PROPERTY;
import static org.unidal.workspace.program.Constants.ELEMENT_PROPERTIES;

import static org.unidal.workspace.program.Constants.ENTITY_BLOCK;
import static org.unidal.workspace.program.Constants.ENTITY_INSTRUMENT;
import static org.unidal.workspace.program.Constants.ENTITY_PROGRAM;
import static org.unidal.workspace.program.Constants.ENTITY_STATUS;

import java.io.IOException;
import java.util.Stack;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParserFactory;

import org.xml.sax.Attributes;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

import org.unidal.workspace.program.IEntity;
import org.unidal.workspace.program.entity.Block;
import org.unidal.workspace.program.entity.Instrument;
import org.unidal.workspace.program.entity.Program;
import org.unidal.workspace.program.entity.Status;

public class DefaultXmlParser extends DefaultHandler {

   private DefaultLinker m_linker = new DefaultLinker(true);

   private DefaultXmlMaker m_maker = new DefaultXmlMaker();

   private Stack<String> m_tags = new Stack<String>();

   private Stack<Object> m_objs = new Stack<Object>();

   private IEntity<?> m_root;

   private StringBuilder m_text = new StringBuilder(256);

   @SuppressWarnings("unchecked")
   public <T extends IEntity<?>> T parse(Class<T> entityType, InputSource input) throws IOException {
      try {
         SAXParserFactory factory = SAXParserFactory.newInstance();

         factory.setValidating(false);
         factory.setFeature("http://xml.org/sax/features/validation", false);
         factory.newSAXParser().parse(input, this);

         m_linker.finish();

         if (entityType.isAssignableFrom(m_root.getClass())) {
            return (T) m_root;
         } else {
            throw new IllegalArgumentException(String.format("Expected %s, but was %s", entityType, m_root.getClass()));
         }
      } catch (ParserConfigurationException e) {
         throw new IllegalStateException("Unable to get SAX Parser! " + e, e);
      } catch (SAXException e) {
         throw new IOException("Unable to parse XML! " + e, e);
      }
   }

   @SuppressWarnings("unchecked")
   protected <T> T convert(Class<T> type, String value, T defaultValue) {
      if (value == null || value.length() == 0) {
         return defaultValue;
      }

      if (type == Boolean.class) {
         return (T) Boolean.valueOf(value);
      } else if (type == Integer.class) {
         return (T) Integer.valueOf(value);
      } else if (type == Long.class) {
         return (T) Long.valueOf(value);
      } else if (type == Short.class) {
         return (T) Short.valueOf(value);
      } else if (type == Float.class) {
         return (T) Float.valueOf(value);
      } else if (type == Double.class) {
         return (T) Double.valueOf(value);
      } else if (type == Byte.class) {
         return (T) Byte.valueOf(value);
      } else if (type == Character.class) {
         return (T) (Character) value.charAt(0);
      } else {
         return (T) value;
      }
   }

   @Override
   public void characters(char[] ch, int start, int length) throws SAXException {
      m_text.append(ch, start, length);
   }

   @Override
   public void endElement(String uri, String localName, String qName) throws SAXException {
      if (uri == null || uri.length() == 0) {
         Object currentObj = m_objs.pop();
         String currentTag = m_tags.pop();

         if (currentObj instanceof Block) {
            Block block = (Block) currentObj;

            if (ELEMENT_DEPEND_ON.equals(currentTag)) {
               block.addDependOn(getText());
            }
         } else if (currentObj instanceof Instrument) {
            Instrument instrument = (Instrument) currentObj;

            if (ELEMENT_PROPERTY.equals(currentTag)) {
               instrument.addProperty(getText());
            }
         } else if (currentObj instanceof Status) {
            Status status = (Status) currentObj;

            if (ELEMENT_MESSAGE.equals(currentTag)) {
               status.setMessage(getText());
            }
         }
      }

      m_text.setLength(0);
   }

   protected String getText() {
      return m_text.toString();
   }

   private void parseForBlock(Block parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      if (ELEMENT_DEPEND_ONS.equals(qName) || ELEMENT_DEPEND_ON.equals(qName)) {
         m_objs.push(parentObj);
      } else if (ENTITY_INSTRUMENT.equals(qName)) {
         Instrument instrument = m_maker.buildInstrument(attributes);

         m_linker.onInstrument(parentObj, instrument);
         m_objs.push(instrument);
      } else if (ENTITY_BLOCK.equals(qName)) {
         Block block_ = m_maker.buildBlock(attributes);

         m_linker.onBlock(parentObj, block_);
         m_objs.push(block_);
      } else if (ENTITY_STATUS.equals(qName)) {
         Status status = m_maker.buildStatus(attributes);

         m_linker.onStatus(parentObj, status);
         m_objs.push(status);
      } else {
         throw new SAXException(String.format("Element(%s) is not expected under block!", qName));
      }

      m_tags.push(qName);
   }

   private void parseForInstrument(Instrument parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      if (ELEMENT_PROPERTIES.equals(qName) || ELEMENT_PROPERTY.equals(qName)) {
         m_objs.push(parentObj);
      } else {
         throw new SAXException(String.format("Element(%s) is not expected under instrument!", qName));
      }

      m_tags.push(qName);
   }

   private void parseForProgram(Program parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      if (ENTITY_BLOCK.equals(qName)) {
         Block block_ = m_maker.buildBlock(attributes);

         m_linker.onBlock(parentObj, block_);
         m_objs.push(block_);
      } else {
         throw new SAXException(String.format("Element(%s) is not expected under program!", qName));
      }

      m_tags.push(qName);
   }

   private void parseForStatus(Status parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      if (ELEMENT_MESSAGE.equals(qName)) {
         m_objs.push(parentObj);
      } else {
         throw new SAXException(String.format("Element(%s) is not expected under status!", qName));
      }

      m_tags.push(qName);
   }

   private void parseRoot(String qName, Attributes attributes) throws SAXException {
      if (ENTITY_PROGRAM.equals(qName)) {
         Program program = m_maker.buildProgram(attributes);

         m_root = program;
         m_objs.push(program);
         m_tags.push(qName);
      } else if (ENTITY_BLOCK.equals(qName)) {
         Block block = m_maker.buildBlock(attributes);

         m_root = block;
         m_objs.push(block);
         m_tags.push(qName);
      } else if (ENTITY_INSTRUMENT.equals(qName)) {
         Instrument instrument = m_maker.buildInstrument(attributes);

         m_root = instrument;
         m_objs.push(instrument);
         m_tags.push(qName);
      } else if (ENTITY_STATUS.equals(qName)) {
         Status status = m_maker.buildStatus(attributes);

         m_root = status;
         m_objs.push(status);
         m_tags.push(qName);
      } else {
         throw new SAXException("Unknown root element(" + qName + ") found!");
      }
   }

   @Override
   public void startElement(String uri, String localName, String qName, Attributes attributes) throws SAXException {
      if (uri == null || uri.length() == 0) {
         if (m_objs.isEmpty()) { // root
            parseRoot(qName, attributes);
         } else {
            Object parent = m_objs.peek();
            String tag = m_tags.peek();

            if (parent instanceof Program) {
               parseForProgram((Program) parent, tag, qName, attributes);
            } else if (parent instanceof Block) {
               parseForBlock((Block) parent, tag, qName, attributes);
            } else if (parent instanceof Instrument) {
               parseForInstrument((Instrument) parent, tag, qName, attributes);
            } else if (parent instanceof Status) {
               parseForStatus((Status) parent, tag, qName, attributes);
            } else {
               throw new RuntimeException(String.format("Unknown entity(%s) under %s!", qName, parent.getClass().getName()));
            }
         }

         m_text.setLength(0);
        } else {
         throw new SAXException(String.format("Namespace(%s) is not supported by %s.", uri, this.getClass().getName()));
      }
   }
}
