/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.model.transform;

import org.unidal.workspace.model.IVisitor;
import org.unidal.workspace.model.entity.Project;
import org.unidal.workspace.model.entity.Workspace;

public abstract class BaseVisitor implements IVisitor {
   @Override
   public void visitProject(Project project) {
      for (Project project_ : project.getDependOn()) {
         visitProject(project_);
      }
   }

   @Override
   public void visitWorkspace(Workspace workspace) {
      for (Project project_ : workspace.getProjects().values()) {
         visitProject(project_);
      }
   }
}
