/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.model.transform;

import static org.unidal.workspace.model.Constants.ATTR_FOR;
import static org.unidal.workspace.model.Constants.ATTR_NAME;

import org.xml.sax.Attributes;

import org.unidal.workspace.model.entity.Project;
import org.unidal.workspace.model.entity.Workspace;

public class DefaultXmlMaker {

   public Project buildProject(Attributes attributes) {
      String name = attributes.getValue(ATTR_NAME);
      Project project = new Project(name);

      return project;
   }

   public Workspace buildWorkspace(Attributes attributes) {
      String _for = attributes.getValue(ATTR_FOR);
      Workspace workspace = new Workspace();

      if (_for != null) {
         workspace.setFor(_for);
      }

      return workspace;
   }

   @SuppressWarnings("unchecked")
   protected <T> T convert(Class<T> type, String value, T defaultValue) {
      if (value == null || value.length() == 0) {
         return defaultValue;
      }

      if (type == Boolean.class || type == Boolean.TYPE) {
         return (T) Boolean.valueOf(value);
      } else if (type == Integer.class || type == Integer.TYPE) {
         return (T) Integer.valueOf(value);
      } else if (type == Long.class || type == Long.TYPE) {
         return (T) Long.valueOf(value);
      } else if (type == Short.class || type == Short.TYPE) {
         return (T) Short.valueOf(value);
      } else if (type == Float.class || type == Float.TYPE) {
         return (T) Float.valueOf(value);
      } else if (type == Double.class || type == Double.TYPE) {
         return (T) Double.valueOf(value);
      } else if (type == Byte.class || type == Byte.TYPE) {
         return (T) Byte.valueOf(value);
      } else if (type == Character.class || type == Character.TYPE) {
         return (T) (Character) value.charAt(0);
      } else {
         return (T) value;
      }
   }
}
