/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.model.transform;

import java.util.ArrayList;
import java.util.List;
import org.unidal.workspace.model.entity.Project;
import org.unidal.workspace.model.entity.Workspace;

public class DefaultLinker {
   @SuppressWarnings("unused")
   private boolean m_deferrable;

   private List<Runnable> m_deferedJobs = new ArrayList<Runnable>();

   public DefaultLinker(boolean deferrable) {
      m_deferrable = deferrable;
   }

   public void finish() {
      for (Runnable job : m_deferedJobs) {
         job.run();
      }
   }

   public boolean onProject(final Workspace parent, final Project project) {
      parent.addProject(project);
      return true;
   }

   public boolean onProject(final Project parent, final Project project) {
      parent.addProject(project);
      return true;
   }
}
