/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.program.entity;

import org.unidal.workspace.program.BaseEntity;
import org.unidal.workspace.program.IVisitor;

public class Status extends BaseEntity<Status> {
   private Boolean m_ignored;

   private Boolean m_skipped;

   private Boolean m_error;

   private Boolean m_updated;

   private String m_message;

   public Status() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitStatus(this);
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof Status) {
         Status _o = (Status) obj;

         if (!equals(getIgnored(), _o.getIgnored())) {
            return false;
         }

         if (!equals(getSkipped(), _o.getSkipped())) {
            return false;
         }

         if (!equals(getError(), _o.getError())) {
            return false;
         }

         if (!equals(getUpdated(), _o.getUpdated())) {
            return false;
         }

         if (!equals(getMessage(), _o.getMessage())) {
            return false;
         }


         return true;
      }

      return false;
   }

   public Boolean getError() {
      return m_error;
   }

   public Boolean getIgnored() {
      return m_ignored;
   }

   public String getMessage() {
      return m_message;
   }

   public Boolean getSkipped() {
      return m_skipped;
   }

   public Boolean getUpdated() {
      return m_updated;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_ignored == null ? 0 : m_ignored.hashCode());
      hash = hash * 31 + (m_skipped == null ? 0 : m_skipped.hashCode());
      hash = hash * 31 + (m_error == null ? 0 : m_error.hashCode());
      hash = hash * 31 + (m_updated == null ? 0 : m_updated.hashCode());
      hash = hash * 31 + (m_message == null ? 0 : m_message.hashCode());

      return hash;
   }

   public boolean isError() {
      return m_error != null && m_error.booleanValue();
   }

   public boolean isIgnored() {
      return m_ignored != null && m_ignored.booleanValue();
   }

   public boolean isSkipped() {
      return m_skipped != null && m_skipped.booleanValue();
   }

   public boolean isUpdated() {
      return m_updated != null && m_updated.booleanValue();
   }

   @Override
   public void mergeAttributes(Status other) {
      if (other.getIgnored() != null) {
         m_ignored = other.getIgnored();
      }

      if (other.getSkipped() != null) {
         m_skipped = other.getSkipped();
      }

      if (other.getError() != null) {
         m_error = other.getError();
      }

      if (other.getUpdated() != null) {
         m_updated = other.getUpdated();
      }
   }

   public Status setError(Boolean error) {
      m_error = error;
      return this;
   }

   public Status setIgnored(Boolean ignored) {
      m_ignored = ignored;
      return this;
   }

   public Status setMessage(String message) {
      m_message = message;
      return this;
   }

   public Status setSkipped(Boolean skipped) {
      m_skipped = skipped;
      return this;
   }

   public Status setUpdated(Boolean updated) {
      m_updated = updated;
      return this;
   }

}
