/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.program;

public class Constants {

   public static final String ATTR_ID = "id";

   public static final String ATTR_IGNORED = "ignored";

   public static final String ATTR_NAME = "name";

   public static final String ATTR_ORDER = "order";

   public static final String ATTR_TYPE = "type";

   public static final String ELEMENT_DEPEND_ON = "depend-on";

   public static final String ELEMENT_DEPEND_ONS = "depend-ons";

   public static final String ELEMENT_PROPERTY = "property";

   public static final String ELEMENT_PROPERTIES = "properties";

   public static final String ENTITY_BLOCK = "block";

   public static final String ENTITY_INSTRUMENT = "instrument";

   public static final String ENTITY_PROGRAM = "program";

   public static final String ENTITY_BLOCKS = "blocks";

   public static final String ENTITY_INSTRUMENTS = "instruments";
}
