/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.program;

import org.unidal.workspace.program.entity.Block;
import org.unidal.workspace.program.entity.Instrument;
import org.unidal.workspace.program.entity.Program;

public interface IVisitor {

   public void visitBlock(Block block);

   public void visitInstrument(Instrument instrument);

   public void visitProgram(Program program);
}
