/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.model;

public class Constants {

   public static final String ATTR_ENABLED = "enabled";

   public static final String ATTR_FOR = "for";

   public static final String ATTR_NAME = "name";

   public static final String ATTR_TYPE = "type";

   public static final String ELEMENT_DOCKER_BUILD_ARGS = "docker-build-args";

   public static final String ELEMENT_GIT_CLONE_ARGS = "git-clone-args";

   public static final String ELEMENT_GIT_PULL_ARGS = "git-pull-args";

   public static final String ELEMENT_GIT_URL = "git-url";

   public static final String ELEMENT_JDK_VERSION = "jdk-version";

   public static final String ELEMENT_KUBECTL_APPLY_ARGS = "kubectl-apply-args";

   public static final String ELEMENT_MVN_INSTALL_ARGS = "mvn-install-args";

   public static final String ELEMENT_MVN_TEST_ARGS = "mvn-test-args";

   public static final String ELEMENT_TEXT = "text";

   public static final String ENTITY_PROJECT = "project";

   public static final String ENTITY_WORKSPACE = "workspace";

   public static final String ENTITY_DEPEND_ON = "depend-on";

   public static final String ENTITY_PROJECTS = "projects";
}
