/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.model;

public class Constants {

   public static final String ATTR_ENABLED = "enabled";

   public static final String ATTR_FOR = "for";

   public static final String ATTR_NAME = "name";

   public static final String ELEMENT_GIT_URL = "git-url";

   public static final String ELEMENT_MVN_ARGS = "mvn-args";

   public static final String ELEMENT_TEXT = "text";

   public static final String ENTITY_PROJECT = "project";

   public static final String ENTITY_WORKSPACE = "workspace";

   public static final String ENTITY_DEPEND_ON = "depend-on";

   public static final String ENTITY_PROJECTS = "projects";
}
