/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.workspace.model;

import org.unidal.workspace.model.entity.Project;
import org.unidal.workspace.model.entity.Workspace;

public interface IVisitor {

   public void visitProject(Project project);

   public void visitWorkspace(Workspace workspace);
}
